[theme]
base="dark"
primaryColor="#6ccb11"
backgroundColor="#062460"
secondaryBackgroundColor="#2742c9"

[server]
headless = true
port = 10000

[browser]
serverAddress = "0.0.0.0"
serverPort = 10000
[server]
headless = true
address = "0.0.0.0"  # Allow access from external IPs
port = 8501  # Use the appropriate port
